### PR TITLE
Npm: Guard against npmrc lines without an equal sign

### LINKED ISSUE #1679: IndexOutOfBoundsException when reading .npmrc file
I get this error when running Analyzer over an NPM project:
```
15:31:33.359 ERROR - Resolving dependencies for 'package.json' in 'D:\tfs\NEO\dev02\src\idm\Presentation\UI\UX\package.json', failed with: Index: 1, Size: 1
15:31:33.359 ERROR - java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at com.here.ort.analyzer.managers.Npm$applyProxySettingsFromNpmrc$1$1.invoke(Npm.kt:187)
        at com.here.ort.analyzer.managers.Npm$applyProxySettingsFromNpmrc$1$1.invoke(Npm.kt:75)
        at kotlin.io.TextStreamsKt.forEachLine(ReadWrite.kt:160)
        at kotlin.io.FilesKt__FileReadWriteKt.forEachLine(FileReadWrite.kt:166)
        at kotlin.io.FilesKt__FileReadWriteKt.forEachLine$default(FileReadWrite.kt:164)
        at com.here.ort.analyzer.managers.Npm$applyProxySettingsFromNpmrc$1.invoke(Npm.kt:186)
        at com.here.ort.analyzer.managers.Npm$applyProxySettingsFromNpmrc$1.invoke(Npm.kt:75)
        at com.here.ort.utils.OkHttpClientHelper.execute(OkHttpClientHelper.kt:105)
        at com.here.ort.analyzer.managers.Npm.parseInstalledModules(Npm.kt:270)
        at com.here.ort.analyzer.managers.Npm.resolveDependencies(Npm.kt:162)
        at com.here.ort.analyzer.PackageManager.resolveDependencies(PackageManager.kt:212)
        at com.here.ort.analyzer.Analyzer.analyze(Analyzer.kt:110)
        at com.here.ort.commands.AnalyzerCommand.runCommand(AnalyzerCommand.kt:156)
        at com.here.ort.CommandWithHelp.run(CommandWithHelp.kt:53)
        at com.here.ort.Main.runCommand(Main.kt:112)
        at com.here.ort.CommandWithHelp.run(CommandWithHelp.kt:53)
        at com.here.ort.Main.run(Main.kt:95)
        at com.here.ort.Main.main(Main.kt:75)
```
(btw. stacktrace printing is not available by default)

And in my `~/.npmrc` I have:
```
proxy=null
https-proxy=null
```

### PR DESCRIPTION
**Pull request by sschuberth**
Fixes #1679.

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch-si.com>

### CODE REVIEW

File: analyzer/src/main/kotlin/managers/Npm.kt [hunk 1]
```diff
@@ -184,16 +184,18 @@ open class Npm(
...
+                    val proxyUrl = value.takeIf { it.matches(HTTP_REGEX) } ?: when (key) {
+                        "proxy" -> "http://$value"
+                        "https-proxy" -> "https://$value"
+                        else -> ""
+                    }
 
-                if (proxyUrl.isNotEmpty()) {
-                    applyProxySettingsFromUrl(URL(proxyUrl))
+                    if (proxyUrl.isNotEmpty()) {
+                        applyProxySettingsFromUrl(URL(proxyUrl))
```
Comment (fviernau) [inline analyzer/src/main/kotlin/managers/Npm.kt]: out of scope of this change / PR: do we want to gracefully handle also `MalformedURLException`s?

Comment (sschuberth) [reply analyzer/src/main/kotlin/managers/Npm.kt]: Good point, probably yes. I'll create a follow-up PR.

Comment (sschuberth) [reply analyzer/src/main/kotlin/managers/Npm.kt]: See https://github.com/heremaps/oss-review-toolkit/pull/1682.
