### PR TITLE
Downloader: Force deletion of VCS left-overs

### LINKED ISSUE #2072: [scanner] DotNet  - AccessDeniedException
Hello,

I m running ORT on windows with a git bash in admin mode.
The scanner step failed without a result file.
I ve got this access denied error : 
```
08:09:16.936 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture - ScanCode version 3.0.2
08:09:16.936 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture -
08:09:16.936 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture -
08:09:16.939 [ScanCode-1] INFO  com.here.ort.scanner.storages.FileBasedStorage - Could not read scan results for 'nuget::Microsoft.AspNetCore.Authorization.Policy:2.0.0' from path 'nuget/unknown/Microsoft.AspNetCore.Authorization.Policy/2.0.0/scan-results.yml': FileNotFoundException: D:\Users\j.dupont\.ort\scanner\results\nuget\unknown\Microsoft.AspNetCore.Authorization.Policy\2.0.0\scan-results.yml (Le chemin d▒acc▒s sp▒cifi▒ est introuvable)
08:09:17.195 [ScanCode-1] INFO  com.here.ort.scanner.storages.FileBasedStorage - Stored scan result for 'nuget::Microsoft.AspNetCore.Authorization.Policy:2.0.0' at path 'nuget/unknown/Microsoft.AspNetCore.Authorization.Policy/2.0.0/scan-results.yml'.
08:09:17.195 [ScanCode-1] INFO  kotlinx.coroutines.CoroutineScope - Finished scanning nuget::Microsoft.AspNetCore.Authorization.Policy:2.0.0 (6/209).
Exception in thread "main" java.nio.file.AccessDeniedException: C:\workspace\POCs\MOB_ORT\thesubstitute\src\my.project\reports\downloads\DotNet\unknown\my.project.csproj\unknown\.git\objects\pack\pack-598131a86f4c8d633a21b414c0eba26b499006c2.idx
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:270)
        at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
        at java.base/java.nio.file.Files.delete(Files.java:1141)
        at com.here.ort.utils.ExtensionsKt$safeDeleteRecursively$1.visitFile(Extensions.kt:141)
        at com.here.ort.utils.ExtensionsKt$safeDeleteRecursively$1.visitFile(Extensions.kt:128)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2724)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
        at com.here.ort.utils.ExtensionsKt.safeDeleteRecursively(Extensions.kt:128)
        at com.here.ort.utils.ExtensionsKt.safeDeleteRecursively$default(Extensions.kt:121)
        at com.here.ort.downloader.Downloader.downloadFromVcs(Downloader.kt:250)
        at com.here.ort.downloader.Downloader.download(Downloader.kt:144)
        at com.here.ort.downloader.Downloader.download$default(Downloader.kt:129)
        at com.here.ort.scanner.LocalScanner.scanPackage(LocalScanner.kt:290)
        at com.here.ort.scanner.LocalScanner.access$scanPackage(LocalScanner.kt:74)
        at com.here.ort.scanner.LocalScanner$scanPackages$2$invokeSuspend$$inlined$map$lambda$1$4.invokeSuspend(LocalScanner.kt:194)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
any idea? 

Regards

### PR DESCRIPTION
**Pull request by sschuberth**
Git creates its pack files with read-onyl attribute set on Windows,
which requires to apply force when deleting them.

Also see e.g. the discussion at
https://github.com/libgit2/libgit2sharp/issues/1354#issuecomment-277968633.

Fixes #2072.

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch-si.com>

### CODE REVIEW

File: downloader/src/main/kotlin/Downloader.kt [hunk 1]
```diff
@@ -249,7 +249,7 @@ class Downloader {
                 }
 
                 // Clean up any files left from the failed VCS download (i.e. a ".git" directory).
-                outputDirectory.safeDeleteRecursively()
+                outputDirectory.safeDeleteRecursively(force = true)
```
Comment (fviernau) [inline downloader/src/main/kotlin/Downloader.kt]: commit-msg: read-onyl -> read only

Comment (sschuberth) [reply downloader/src/main/kotlin/Downloader.kt]: Fixed.
