### PR TITLE
MavenSupport: Work around the common mistake to omit the provider

### LINKED ISSUE #2191: Scanning quits when trying to download from invalid URL
When I scan the results of the analyzer, the scanning process will quit when sources for a dependency cannot be downloaded due to an invalid URL.

This is the stacktrace:

````
Exception in thread "main" org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of ls-remote command
        at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:218)
        at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:161)
        at com.here.ort.downloader.vcs.GitWorkingTree.listRemoteTags(GitWorkingTree.kt:116)
        at com.here.ort.downloader.WorkingTree.guessRevisionName(WorkingTree.kt:89)
        at com.here.ort.downloader.VersionControlSystem.download(VersionControlSystem.kt:261)
        at com.here.ort.downloader.VersionControlSystem.download$default(VersionControlSystem.kt:226)
        at com.here.ort.downloader.Downloader.downloadFromVcs(Downloader.kt:256)
        at com.here.ort.downloader.Downloader.download(Downloader.kt:144)
        at com.here.ort.downloader.Downloader.download$default(Downloader.kt:129)
        at com.here.ort.scanner.LocalScanner.scanPackage(LocalScanner.kt:287)
        at com.here.ort.scanner.LocalScanner.access$scanPackage(LocalScanner.kt:75)
        at com.here.ort.scanner.LocalScanner$scanPackages$2$invokeSuspend$$inlined$map$lambda$1$4.invokeSuspend(LocalScanner.kt:195)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.eclipse.jgit.errors.NotSupportedException: URI not supported: file://author-name@github.com/author-name/mylib.git
        at org.eclipse.jgit.transport.Transport.open(Transport.java:561)
        at org.eclipse.jgit.transport.Transport.open(Transport.java:429)
        at org.eclipse.jgit.transport.Transport.open(Transport.java:308)
        at org.eclipse.jgit.transport.Transport.open(Transport.java:276)
        at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:188)
````

As you can see, the analyser found a a VCS URL of the form `file://author-name@github.com/author-name/mylib.git` which cannot be used for downloading files. A `DownloadException` is not thrown in this case.

When I fix the URL to `https://github.com/author-name/mylib.git`, the scanner/downloader works as expected.

I have been advised to ping @sschuberth on this issue. ;-)

Thank you.
Uwe

### PR DESCRIPTION
**Pull request by sschuberth**
Resolves #2191.

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>

### CODE REVIEW

File: analyzer/src/main/kotlin/managers/utils/MavenSupport.kt [hunk 1]
```diff
@@ -177,6 +178,15 @@ class MavenSupport(workspaceReader: WorkspaceReader) {
                             VcsInfo(type = VcsType.SUBVERSION, url = url, revision = "", path = path)
                         }
 
+                        type == "http" || type == "https" -> {
```
Comment (mnonnenmacher) [inline analyzer/src/main/kotlin/managers/utils/MavenSupport.kt]: What about checking instead if the url starts with "//"? This would also catch entries like this one I saw recently:
`<connection>scm:git://github.com/vigna/fastutil.git</connection>`

Comment (sschuberth) [reply analyzer/src/main/kotlin/managers/utils/MavenSupport.kt]: Good idea, will do that.

**Comment by sschuberth** [comment]
> Are the code paths covered actually include Gitub specific logic?

Yes, they do, as `splitUrl()` uses the `VcsHost` class.
